spring.application.name=LanguageStudyTracker
spring.datasource.url=jdbc:mysql://localhost:3306/language_tracker_db
spring.datasource.username=root
spring.datasource.password=wweraw01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true